[package]
name = "rust-web-framework"
version = "0.1.0"
edition = "2021"

[dependencies]
flate2 = "1.1.0"
http = "1.3.1"
futures = { version = "0.3.31", features = ["thread-pool"] }
anyhow = "1.0.98"
thiserror = "2.0.12"
